services:
  huge-ifx-api:
    container_name: huge-ifx-api
    build:
      context: ./api
      target: base
    volumes:
      - ./:/workspace
      - ./api:/code # TODO: move to devcontainer.json
      - root-history:/root/history
      - vscode-server:/root/.vscode-server
      - huggingface-cache:/root/.cache/huggingface
      - google-vscode-extension-cache:/root/.cache/google-vscode-extension
      - ~/.gemini:/root/.gemini
      - /var/run/docker.sock:/var/run/docker.sock # expose docker socket
    stdin_open: true
    tty: true
    ports:
      - "8000:8000" # serving site
      - "5678:5678" # debugger
    env_file:
      - .env
    environment:
      DEBUG: false
      GOOGLE_CLOUD_PROJECT: gemini-code-assist-466218
    # command: uvicorn server:app --reload --host 0.0.0.0 --port 8000 --reload --log-level debug
    command: gradio server_gradio.py

volumes:
  root-history:
    name: root-history
    external: true
  vscode-server:
    name: vscode-server
    external: true
  huggingface-cache:
    name: huggingface-cache
    external: true
  google-vscode-extension-cache:
    name: google-vscode-extension-cache
    external: true
